# Generated by Django 3.0.1 on 2020-02-05 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapadmin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
