# Generated by Django 3.0.1 on 2020-02-26 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapadmin', '0004_blog_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_comment',
        ),
    ]
