# Generated by Django 3.0.1 on 2019-12-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Completed', 'Completed'), ('in_process', 'in-process'), ('not_started', 'Not started')], max_length=20),
        ),
    ]
