# Generated by Django 3.0.1 on 2020-01-18 08:04

import Tap_admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0007_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=Tap_admin.models.user_directory_path)),
            ],
        ),
    ]
