# Generated by Django 3.0.1 on 2020-02-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0010_auto_20200130_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.BigIntegerField(null=True),
        ),
    ]
