# Generated by Django 3.0.1 on 2020-02-11 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0011_auto_20200205_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], max_length=20),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='property image/')),
                ('image2', models.ImageField(upload_to='property image/')),
                ('image3', models.ImageField(upload_to='property image/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tap_admin.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Residential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_building', models.IntegerField()),
                ('no_of_floor', models.IntegerField()),
                ('no_of_1bhk', models.IntegerField()),
                ('no_of_2bhk', models.IntegerField()),
                ('no_of_3bhk', models.IntegerField()),
                ('no_of_4bhk', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tap_admin.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Commercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_floor', models.IntegerField()),
                ('no_of_office', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tap_admin.Project')),
            ],
        ),
    ]
