# Generated by Django 3.0.1 on 2020-02-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0012_auto_20200211_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image1',
            field=models.ImageField(null=True, upload_to='property image/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image2',
            field=models.ImageField(null=True, upload_to='property image/'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='image3',
            field=models.ImageField(null=True, upload_to='property image/'),
        ),
    ]
