# Generated by Django 3.0.1 on 2020-02-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0013_auto_20200211_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residential',
            name='project',
        ),
        migrations.DeleteModel(
            name='Commercial',
        ),
        migrations.DeleteModel(
            name='Residential',
        ),
    ]
