# Generated by Django 3.0.1 on 2020-02-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0015_commercial_residential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residential',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tap_admin.Project'),
        ),
    ]
