# Generated by Django 3.0.1 on 2020-02-26 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0017_project_project_disciption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_disciption',
            new_name='project_desciption',
        ),
    ]
