# Generated by Django 3.0.1 on 2020-03-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0018_auto_20200226_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='purchased_date',
            field=models.DateField(null=True),
        ),
    ]
