# Generated by Django 3.0.1 on 2020-03-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tap_admin', '0019_auto_20200305_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='bought_status',
            field=models.CharField(default='Not bought', max_length=30),
        ),
        migrations.AddField(
            model_name='material',
            name='user',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
