# Generated by Django 3.0.4 on 2020-03-23 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_auto_20200307_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='district',
        ),
    ]
